### ISSUE TITLE
切换解码会崩溃

### ISSUE THREAD

**Issue by LydixLiu** [umdk/UCDMediaPlayer_iOS#1]
切换硬解码程序会崩溃，提示selectDecodeMethod:方法未实现

**Comment by grubbyliu** [comment]
@LydixLiu ，非常抱歉，这个方法因为修改API命名导致失效了，你可以使用刚更新的版本https://github.com/umdk/UCDMediaPlayer_iOS/tree/v1.4.0  来解决问题。
PS：硬解只能支持系统原生支持的解码格式和协议，建议HTTP-MP4、HTTP-HLS点播文件以外的选择软解更好
